lastdraft_post:
    # author:
    #     model:      Acme\Bundle\PostBundle\Entity\Author
    #     repository: Acme\Bundle\PostBundle\Repository\AuthorRepository

    # post:
    #     model:      Acme\Bundle\PostBundle\Entity\Post
    #     repository: Acme\Bundle\PostBundle\Repository\AuthorRepository
