lastdraft_post:
    author:
        model:      Lastdraft\Bundle\PostBundle\Model\Author
        repository: Lastdraft\Bundle\PostBundle\Repository\AuthorRepository

    post:
        model:      Lastdraft\Bundle\PostBundle\Model\Post
        repository: Lastdraft\Bundle\PostBundle\Repository\AuthorRepository
