lastdraft_post:
    author:
        model:      Lastdraft\Bundle\PostBundle\Entity\Author
        repository: Lastdraft\Bundle\PostBundle\Repository\AuthorRepository

    post:
        model:      Lastdraft\Bundle\PostBundle\Entity\Post
        repository: Lastdraft\Bundle\PostBundle\Repository\AuthorRepository
